version: '3'

tasks:
  dev:
    desc: "Run service in dev mode."
    cmd: go run ./cmd/main.go
  
  init_db:
    desc: "Initiate a database for dev purposes."
    cmd: cd scripts && bash ./init_database.sh

  migrate:
    desc: "Create a new migration file using goose"
    cmd: cd scripts && bash ./goose_add_migration.sh

  docs:
    desc: "Generate swagger.json from annotations"
    cmd: swag init -g cmd/main.go --dir ./ -o api/docs --outputTypes json

  test:
    desc: "Run tests"
    cmd: gotestsum --format testname ./tests/...

