#!/bin/bash
set -e

SCHEMA="${DB_SCHEMA:-core}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE SCHEMA IF NOT EXISTS $SCHEMA AUTHORIZATION $POSTGRES_USER;
  GRANT USAGE ON SCHEMA $SCHEMA TO $POSTGRES_USER;
  GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA $SCHEMA TO $POSTGRES_USER;
  ALTER DEFAULT PRIVILEGES IN SCHEMA $SCHEMA
      GRANT SELECT, INSERT, UPDATE ON TABLES TO $POSTGRES_USER;
  ALTER DATABASE $POSTGRES_DB SET search_path TO $SCHEMA, public;
EOSQL

echo "Schema '$SCHEMA' initialized for database '$POSTGRES_DB'."
